**1. The most basic kind of broadcast is with a scalar, in which you can perform a binary
operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to perform that
operation with the scalar for every element of the array. To try this out, create a vector
1, 2, . . . , 10 by adding 1 to the result of the arange function.**

In [17]:
import numpy as np      
vector= np.arange(1,11)         #using arange function to generate vector with 1 X 10
result_vector=vector+1
print(result_vector)


[ 2  3  4  5  6  7  8  9 10 11]


**2. Now, create a 10 × 10 matrix A in which A[i][j] = i + j. You’ll be able to do this using
the vector you just created, and adding it to a reshaped version of itself**

In [ ]:
import numpy as np
B=np.reshape((np.arange(1,101)),(-1,10))  # creating a 10 X 10 matrix with random values 
A=B+B                                     # a[i][j]=i+j which is adding the matrix to itself



**3. Now, compute the mean and standard deviation of each column. This should result in
two vectors of length 5. You’ll need to think a little bit about how to use the axis
argument to mean and std. Store these vectors into variables and print both of them.**

In [8]:
import numpy as np
import numpy.random as npr   #using random module to generate random values
data = ( npr.randn(50, 5) )  #creating a matrix of 50 X 5
Mean_data=np.mean(data,axis=0)  #finding the mean of given value in terms of column wise
Std_data=np.std(data,axis=0)    # standard deviation of the data in terms of column wise
print(Mean_data)
print(Std_data)

[ 0.29124367 -0.09557695 -0.16104869  0.08112663  0.10071195]
[0.8833859  0.86047177 0.97475709 0.93961521 1.03315048]


**5. Now standardize the data matrix by**
**1.  subtracting the mean off of each column, and**
**2.  dividing each column by its standard deviation. Do this via broadcasting, and store the result in a matrix called normalized. 
To verify that you successfully did it, compute
the mean and standard deviation of the columns of normalized and print them out.**

In [11]:

import numpy as np
import numpy.random as npr              #using random module to generate random values
data = np.exp (npr.randn(50, 5))        #creating a matrix of 50 X 5
Mean_of_data=np.mean(data,axis=0)       #finding the mean of given value in terms of column wise
Std_data=np.std(data,axis=0)            # standard deviation of the data in terms of column wise                    
normalized=np.divide((np.subtract(data,Mean_of_data)),Std_data)  #creating new matrix with given condition in the question by first subtracting  mean value for each column and dividing with standard deviation
normalized_mean=np.mean(normalize,axis=0)   #computing new mean for the normalized data
normalized_std=np.std(normalize,axis=0)     #computing new standard deviation for the normalized data
print("data= ",data)
print("Mean of data =" ,Mean_of_data)
print("std deviation of data =" ,Std_data)
print("normalized data =",normalized)
print("nm",normalized_mean)
print("n std =", normalized_std)
"The normalized mean will be equivalent to zero and std deviation will be 1"


data=  [[ 2.30172172  1.18959139  1.56880383  7.95868637  3.30404414]
 [ 4.76316462  2.88124537  2.87769433  1.6631079   0.50462187]
 [ 1.84788213  1.90280617  1.23413312  0.56440276  0.37149967]
 [ 1.73658616  2.15800666  0.25887321  3.17559699  0.39421746]
 [ 0.515634    0.56971069  0.75831613 18.73702808  1.91163967]
 [ 1.9969574   4.24046655  2.68245565  2.69889444 12.13187974]
 [ 1.48808763  4.3194257   1.95171064  0.38165482  1.78281209]
 [ 4.72349818  0.66718529  0.66827808  2.70378607  0.27260844]
 [ 0.35584402  5.86580933  0.15869647  0.78789804  0.75766062]
 [ 2.80696676  6.34626534  1.03083993  1.10573073  2.62126438]
 [13.21974858  3.55987032  0.32970489  1.42429723  1.03379549]
 [ 0.32537209  2.53070432  1.04306731  0.55599912  0.86276427]
 [ 1.37871055  0.17419941  1.74178303  0.87435451  2.21272068]
 [ 0.3808129   0.47465302  1.52002282  4.46075498  0.36727304]
 [ 0.27538455  5.20538918  0.19606324  2.52763428  4.27720612]
 [ 0.39766911  0.58155352  0.4869876   0.6914321

'The normalized mean will be equivalent to zero and std deviation will be 1'

**Part-2**

**Aim: Performing the Hypothesis testing using the Chi-squared test
The table below is a survey response to 4 categorical variables: people in categories from
18–29, 30–44, 45–64 and >65 years, and their movie genre inclination, which is
“Action/Adventure”, “Romance” and “Biography”. Is there any evidence of a relationship
between the age group and their movie genre inclination, at 5% significance level?**

In [5]:
import numpy as np
from scipy.stats import chi2_contingency                       #importing chi2_contigency module from scipy
age_groupdata=[[141,68,4],[179,159,7],[220,216,4],[86,101,4]]  #data value considered for this simulation
chi2, P, dof, expected =chi2_contingency(age_groupdata)        #result will be a tuple hence assigning it with respective values
print("P value = ",P)
print("Chi2 value=",chi2)
print("DOF =",dof)
print("Expected vaulues = ",expected)
if P < 0.05:                                                   #rejection or acceptance based on comparision with alpha of 0.05
  print("There is no significance evidence that the age group and their movie genre inclination, the values are independent")

P value =  0.00044690833914947634
DOF = 6
Expected vaulues =  [[112.14297729  97.45332212   3.40370059]
 [181.64003364 157.84693019   5.51303616]
 [231.6568545  201.31202691   7.03111859]
 [100.56013457  87.38772077   3.05214466]]
There is no significance evidence that the age group and their movie genre inclination, the values are independent
